# Lesson 8: Working With Data

In [51]:
import pandas as pd
import numpy as np

In [52]:
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/PUBH1142Chap0801.csv')

type(df)

pandas.core.frame.DataFrame

## Data Overview

In [53]:
df.head()

df.shape

df.columns

df.ndim

df.size

df.dtypes

Name                  object
DOB                   object
Age                    int64
Vocation              object
Smoke                  int64
HR                     int64
sBP                    int64
CholesterolBefore    float64
TAG                  float64
Survey                 int64
CholesterolAfter     float64
Delta                float64
Group                 object
dtype: object

## Task 1: Vocation Column

In [54]:
vocation = df.Vocation

type(vocation)

vocation.tail()

195            Sales professional, IT
196                         Paramedic
197    Chartered certified accountant
198                            Dancer
199                Theme park manager
Name: Vocation, dtype: object

In [55]:
age_column = df.Age

age = age_column.to_numpy()

type(age)

age_column.mean()

age_column.min()

age_column.max()

75

## Selecting Rows and Columns

In [56]:
df.iloc[:5, [0, 2]]
df.loc[:4, ['Name', 'Age']]

                Name  Age
0       Dylan Patton   43
1      Sandra Howard   53
2  Samantha Williams   33
3     Ashley Hensley   43
4      Robert Wilson   46

## Task 2: TAG and Smoke (Rows 10-15)

In [57]:
df.loc[10:15, ['TAG', 'Smoke']]

    TAG  Smoke
10  1.7      0
11  2.0      0
12  2.3      0
13  2.1      0
14  2.4      0
15  2.6      2

## Task 3: Ages of Non-Smokers

In [58]:
age_nonsmokers = df.loc[df.Smoke == 0, 'Age']
age_nonsmokers

0      43
1      53
2      33
3      43
4      46
       ..
180    74
183    62
188    41
193    61
197    61
Name: Age, Length: 88, dtype: int64

In [59]:
age_nonsmokers.mean()

np.float64(50.09090909090909)

## Task 4: Non-smokers with survey = 3

In [60]:
non_smokers_choice_3 = df.loc[(df.Smoke == 0) & (df.Survey == 3), 'Age']
non_smokers_choice_3

1      53
2      33
11     35
14     57
27     47
32     54
38     45
45     54
50     53
112    36
130    68
183    62
Name: Age, dtype: int64

## Task 5: Multiple Conditions (Age and TAG as NumPy Array)

In [61]:
selection = (df.Smoke == 0) & (df.HR < 80) & (df.sBP < 120)

In [62]:
df.loc[selection, ['Age', 'TAG']].to_numpy()

array([[53. ,  0.6],
       [43. ,  1.6],
       [44. ,  2.4],
       [35. ,  2. ],
       [45. ,  2.1],
       [55. ,  3.1]])

## Task 6: Participants Younger Than 50

In [63]:
df_younger_than_50 = df.loc[df.Age < 50]
df_younger_than_50

,Name,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active
2,Samantha Williams,1973-12-21,33,IT consultant,0,54,120,2.0,1.3,3,1.7,0.3,Active
3,Ashley Hensley,1981-12-01,43,"Nurse, children's",0,54,103,2.1,1.6,4,2.1,0.0,Active
4,Robert Wilson,1964-06-23,46,Clinical embryologist,0,61,138,2.8,2.1,5,2.8,0.0,Active
5,Leslie Diaz,1994-08-25,48,Politician's assistant,0,59,122,2.8,1.4,4,2.6,0.2,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Nicole Vance,1990-07-17,43,Personnel officer,1,87,193,8.4,5.0,2,8.2,0.2,Control
176,Alejandro Love,1957-05-03,35,Fashion designer,2,85,167,8.4,4.5,2,8.3,0.1,Control
182,James Rojas,1965-11-02,40,"Solicitor, Scotland",1,44,98,8.7,5.0,1,8.3,0.4,Control
187,Kristie Morris,1994-01-16,45,Senior tax professional/tax inspector,1,91,185,9.0,4.6,4,8.6,0.4,Active
188,Joan Chavez,1999-10-07,41,Energy manager,0,93,182,9.1,5.0,2,8.8,0.3,Control

In [64]:
df_younger_than_50.HR.mean()

np.float64(69.45348837209302)

## Task 7: Filter Specific Job Titles

In [65]:
jobs = ['IT consultant', 'Energy manager', 'Clinical embryologist']

In [66]:
crit = df.Vocation.isin(jobs)

In [67]:
df_jobs = df.loc[crit]
df_jobs

,Name,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active
2,Samantha Williams,1973-12-21,33,IT consultant,0,54,120,2.0,1.3,3,1.7,0.3,Active
4,Robert Wilson,1964-06-23,46,Clinical embryologist,0,61,138,2.8,2.1,5,2.8,0.0,Active
188,Joan Chavez,1999-10-07,41,Energy manager,0,93,182,9.1,5.0,2,8.8,0.3,Control

## Task 8: Filter Jobs Containing "manager"

In [68]:
crit = df.Vocation.str.contains('manager', na=False)

In [69]:
df_manager = df.loc[crit]
df_manager

,Name,DOB,Age,Vocation,Smoke,HR,sBP,CholesterolBefore,TAG,Survey,CholesterolAfter,Delta,Group
0,Dylan Patton,1981-10-07,43,Energy manager,0,47,145,1.2,1.2,1,0.7,0.5,Active
34,Mr. Tyler Strickland DDS,1940-08-27,46,Tourist information centre manager,0,62,136,4.1,2.3,2,3.8,0.3,Control
54,Stephanie Jacobs,1977-06-18,38,Estate manager/land agent,0,69,139,4.4,2.7,2,4.0,0.4,Active
55,Juan Johnson,1956-12-09,51,Logistics and distribution manager,0,65,141,4.5,2.9,5,4.0,0.5,Control
71,Tina Martinez,1941-05-31,74,Passenger transport manager,1,69,146,4.8,3.1,4,4.5,0.3,Active
107,Kelly Rivera,1939-07-05,75,Call centre manager,0,78,170,6.0,3.2,4,5.9,0.1,Active
127,Michael Black,1973-03-18,35,Fish farm manager,0,85,178,7.1,3.9,4,6.9,0.2,Active
130,Stephanie Pruitt,1996-01-09,68,Heritage manager,0,85,186,7.3,3.8,3,7.0,0.3,Active
145,Kevin Shields,1982-04-19,54,Accommodation manager,2,86,190,7.7,4.0,4,7.3,0.4,Active
146,Jennifer Kelly,1970-11-05,66,Public house manager,1,85,189,7.7,4.7,5,7.7,0.0,Control
147,Greg Lewis,1978-01-28,58,Production manager,1,86,191,7.8,4.3,3,7.3,0.5,Control
188,Joan Chavez,1999-10-07,41,Energy manager,0,93,182,9.1,5.0,2,8.8,0.3,Control
199,Julie Barrett,1972-07-27,66,Theme park manager,1,102,208,11.1,5.7,2,10.7,0.4,Active

## Task 9: Rename and Drop Columns

In [70]:
df.rename(columns={'Name': 'Patient'}, inplace=True)
df.columns

Index(['Patient', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Delta',
       'Group'],
      dtype='object')

In [71]:
df.drop(columns='Delta', inplace=True)
df.columns

Index(['Patient', 'DOB', 'Age', 'Vocation', 'Smoke', 'HR', 'sBP',
       'CholesterolBefore', 'TAG', 'Survey', 'CholesterolAfter', 'Group'],
      dtype='object')

## Task 10: Modify Age and Create AgeHR

In [72]:
df.Age = df.Age + 2
df.Age.head()

0    45
1    55
2    35
3    45
4    48
Name: Age, dtype: int64

In [73]:
def add2(x):
    return x + 2

In [74]:
df.Age = df.Age.apply(add2)
df.Age.head()

0    47
1    57
2    37
3    47
4    50
Name: Age, dtype: int64

In [75]:
df['AgeHR'] = df.Age * df.HR
df[['Age', 'HR', 'AgeHR']].head()

   Age  HR  AgeHR
0   47  47   2209
1   57  51   2907
2   37  54   1998
3   47  54   2538
4   50  61   3050

## Task 11: Replace Values and Split Names

In [76]:
df.Group.replace({'Active': 1, 'Control': 0}, inplace=True)
df.Group.head()

/var/folders/l2/br1ybvf53kxdqjf9sv451b5c0000gn/T/ipykernel_15546/1501649206.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Group.replace({'Active': 1, 'Control': 0}, inplace=True)
/var/folders/l2/br1ybvf53kxdqjf9sv451b5c0000gn/T/ipykernel_15546/1501649206.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.Group.replace({'Active': 1, 'Control': 0}, inplace=True)

0    1
1    1
2    1
3    1
4    1
Name: Group, dtype: int64

In [77]:
split_participant = df.Patient.str.split(' ', expand=True)

In [78]:
df['FirstName'] = split_participant[0]
df['LastName'] = split_participant[1]

In [79]:
df[['FirstName', 'LastName', 'Patient']].head()

  FirstName  LastName            Patient
0     Dylan    Patton       Dylan Patton
1    Sandra    Howard      Sandra Howard
2  Samantha  Williams  Samantha Williams
3    Ashley   Hensley     Ashley Hensley
4    Robert    Wilson      Robert Wilson

## Quiz Questions and Answers

In [50]:
# 1. Import pandas
import pandas as pd

# 2. Read CSV (already done earlier, but included for answer)
# df = pd.read_csv('data.csv')

# 3. Display first 5 rows
df.head()

# 4. Number of rows and columns
df.shape

# 5. Column names
df.columns

# 6. Summary info
df.info()

# 7. Select rows where Age > 50 (using real column instead of A)
df[df['Age'] > 50]

# 8. Select two columns (using real columns)
df[['Age', 'HR']]

# 9. Rename a column (example using Age → Age_new)
df.rename(columns={'Age': 'Age_new'}, inplace=True)

# change it back so your dataset stays correct
df.rename(columns={'Age_new': 'Age'}, inplace=True)

# 10. Replace 999 with NaN
import numpy as np
df.replace(999, np.nan, inplace=True)

# 11. Drop rows with missing values
df.dropna()

# 12. Fill missing values with 0
df.fillna(0)

# 13. Mean of Age column
df['Age'].mean()

# 14. Create new column (example using Age + HR)
df['ExampleSum'] = df['Age'] + df['HR']

# 15. Save to CSV
df.to_csv('output.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient            200 non-null    object
 1   DOB                200 non-null    object
 2   Age                200 non-null    int64
 3   Vocation           200 non-null    object
 4   Smoke              200 non-null    int64
 5   HR                 200 non-null    int64
 6   sBP                200 non-null    int64
 7   CholesterolBefore  200 non-null    float64
 8   TAG                200 non-null    float64
 9   Survey             200 non-null    int64
 10  CholesterolAfter   200 non-null    float64
 11  Group              200 non-null    int64
 12  AgeHR              200 non-null    int64
 13  FirstName          200 non-null    object
 14  LastName           200 non-null    object
dtypes: float64(3), int64(7), object(5)
memory usage: 23.6+ KB